version: '3'
    
services:

  backendproxy:
    build: backend-proxy
    image: cumc-dbmi/howoften/backendproxy
    ports:
    - "8080:80"

  backend:
    build: incidence-api
    image: cumc-dbmi/howoften/backend
    environment:
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_HOSTNAME=${DATASOURCE_HOSTNAME}
      - DATASOURCE_PORT=${DATASOURCE_PORT}
      - DATASOURCE_SCHEMA=${DATASOURCE_SCHEMA}
      - DATASOURCE_DATABASE=${DATASOURCE_DATABASE}
    ports:
    - "8085:5000"

  frontend:
    build: client
    image: cumc-dbmi/howoften/frontend
    ports:
     - "80:80"