import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Image from 'next/image'
import Link from "next/link";
import {Providers} from "./providers";
import {FaGithub} from "react-icons/fa";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <title>How Often App - Observational Health Data Sciences and Informatics </title>
        <body className="p-12">
        <Providers>

            <header className="mx-auto max-w-screen-xl flex">
                <div className="flex-1 pl-4"><Link href="\"><Image src="/ohdsi-logo-with-text.png" width="200" height="51" alt="The Observational Health Data Sciences and Informatics Logo"/></Link></div>
                <div className="pr-4"><Link href="https://github.com/cumc-dbmi/drug-condition-incidence"><FaGithub size={51} aria-label="Fork this project"/></Link></div>
            </header>

            {children}

        </Providers>
        </body>
        </html>
    );
}