import './globals.css'
import '@radix-ui/themes/styles.css';
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Theme} from "@radix-ui/themes";
import Image from 'next/image'
import Link from "next/link";


const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html>
        <body>
        <Theme>
           <Link href="\"> <Image
                src="/ohdsi-logo-with-text.png"
                width={200}
                height={51}
                alt="Picture of the author"
           /></Link>
            {children}
        </Theme>
        </body>
        </html>
    );
}