name: Docker Compose and Publish to ACR

on:
  push:
    branches: ["feature/dbmi-cicd"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Display the event that triggered workflow
      run: echo "the job was triggered bu a ${{ github.event_name }} event."

    - name: Display Runner information
      run: echo "This job is now running on  a ${{ runner.os }} server hosted by GitHub"

    - name: Display repository and branch information
      run: echo "The repository is ${{ github.repository }} and the branch is ${{ github.ref }}"

    - name: Checkout code
      uses: actions/checkout@v3

    - run: echo "The {{ github.repository }} repository ihas been cloned to the runner."

    - run: echo "The workflow is now ready to test your code on the runner."

    - name: List files in repository
      run: ls ${{ github.workspace }}
